{{- if .Values.household.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matlistan.fullname" . }}-household
  labels:
    {{- include "matlistan.labels" . | nindent 4 }}
type: Opaque
stringData:
  household.yaml: |
    {{- include "matlistan.householdFile" . | nindent 4 }}
{{- end }}
